name: Deploy DjangoApp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "Noy yet"
      - name: Deploy Heroku 
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} 
          heroku_email: ${{secrets.EMAIL}}
          dontuseforce: false #OPTIONAL and DEFAULT - false
          usedocker: false #OPTIONAL and DEFAULT - false
