name: Deploy DjangoApp

on: [push]

jobs:
  deploy_heroku:
    runs-on: ubuntu-latest
    name: deploy_heroku
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Testing
        run: echo 'Hoka'
      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} 
          heroku_email: ${{secrets.EMAIL}}
          dontuseforce: false #OPTIONAL and DEFAULT - false
          usedocker: false #OPTIONAL and DEFAULT - false
